# Generated by Django 6.0 on 2025-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.JSONField(blank=True, help_text="{'height': ..., 'width': ..., 'thickness': ...}", null=True),
        ),
    ]
