# Generated by Django 6.0 on 2025-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, help_text='International Standard Book Number (if applicable)', max_length=20, null=True, verbose_name='ISBN'),
        ),
    ]
