# Generated by Django 6.0 on 2025-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edition_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de edición'),
        ),
        migrations.AddField(
            model_name='product',
            name='measures',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medidas'),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Páginas'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Año'),
        ),
    ]
