# Generated by Django 6.0 on 2025-12-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(help_text='Use set_password() to hash passwords', max_length=128),
        ),
    ]
