# Generated by Django 6.0 on 2025-12-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_update_customer_password_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, help_text='International Standard Book Number (if applicable)', max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
    ]
